<h3><?=$book->getTitle()?></h3>
<form action="" method="post">
    <div class="form-group">
        <label for="id">Id:</label>
        <input type="number" class="form-control" name="id" value="<?=$book->getId()?>" readonly>
    </div>
    <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" class="form-control" name="title" id="title" value="<?=$book->getTitle()?>"/>
    </div>
    <div class="form-group">
        <label for="description">Description:</label>
        <textarea class="form-control" name="description" id="description" rows="7" cols="50"><?=$book->getDescription()?></textarea>
    </div>
    <div class="form-group">
        <label for="price">Price:</label>
        <input type="text" class="form-control" name="price" id="price" value="<?=$book->getPrice()?> UAH"/>
    </div>
    <div class="form-group">
        <label for="is_active">Is active:</label>
        <input type="text" class="form-control" name="is_active" id="is_active" value="<?=$book->IsActive()?>"/>
    </div>
    <button type="submit" class="btn btn-default">Save</button>
</form>