<h3><?=$book->getTitle()?></h3>

<form action="" method="post">
    <label for="id">Id:</label>
    <input type="number" name="id" value="<?=$book->getId()?>" readonly><br/>
    <label for="title">Title:</label>
    <input type="text" name="title" id="title" value="<?=$book->getTitle()?>"/><br/>
    <label for="description">Description:</label>
    <textarea name="description" id="description" rows="7" cols="50"><?=$book->getDescription()?></textarea><br/>
    <label for="price">Price:</label>
    <input type="text" name="price" id="price" value="<?=$book->getPrice()?> UAH"/><br/>
    <label for="is_active">Is active:</label>
    <input type="text" name="is_active" id="is_active" value="<?=$book->IsActive()?>"/><br/>
    <button  type="submit">Save</button>
</form>

