routes:
  home:
    pattern: '/home/?'
    controller: 'SiteController'
    action: 'indexAction'
  home_alt:
    pattern: '/?'
    controller: 'SiteController'
    action: 'indexAction'
  page_not_found:
    pattern: /notFound/?
    controller: SiteController
    action: 'notFoundAction'
  show_category:
    pattern: /news/category/{category}/page/?{page}/?
    controller: NewsController
    action: categoryAction
    params:
      category: ([a-z]*)
      page: ([0-9]*)
  show_category_analitic:
      pattern: /news/analitic/page/?{page}/?
      controller: NewsController
      action: analiticAction
      params:
        page: ([0-9]*)
  show_new_item:
    pattern: /news/[a-z]+/item/?{id}/?
    controller: NewsController
    action: showAction
    params:
      id: ([0-9]*)
  show_by_tag:
    pattern: /news/filter-tag/page/?{page}/?
    controller: NewsController
    action: showTagAction
    params:
      page: ([0-9]*)
  summary_news_tabe:
    pattern: /admin/news/summary/?
    controller: Admin\NewsController
    action: summaryAction
  news_add:
    pattern: /admin/news/add/?
    controller: Admin\NewsController
    action: addNewsAction
  edit_news:
    pattern: /admin/news/edit-{id}?
    controller: Admin\NewsController
    action: editNewsAction
    params:
      id: ([1-9]{1}[0-9]*)
  admin_delete_new:
    pattern: /admin/news/delete-{id}/?
    controller: Admin\NewsController
    action: deleteAction
    params:
      id: ([1-9]{1}[0-9]*)
  view_categories:
    pattern: /admin/categories/view/?
    controller: Admin\NewsController
    action: viewCategoriesAction
  add_category:
    pattern: /admin/categories/add/?
    controller: Admin\NewsController
    action: addCategoryAction
  manage_adver_block:
    pattern: /admin/edit/advert/?
    controller: Admin\SiteController
    action: advertAction
  manage_menu_site:
    pattern: /admin/manage/menu/?
    controller: Admin\SiteController
    action: manageMenuAction
  add_advert_block:
    pattern: /admin/advert/add/?
    controller: Admin\SiteController
    action: addAdvertAction
  search_by_filters:
    pattern: /news/filters/page/?{page}/?
    controller: NewsController
    action: filtersAction
    params:
      page: ([0-9]*)
  comments_summary_view:
    pattern: /admin/comments/view?
    controller: Admin\SiteController
    action: viewCommentsAction
  comments_politcs_not_approved:
    pattern: /admin/comments/moderate/?
    controller: Admin\SiteController
    action: watingCommentsAction
  comments_add:
    pattern: /comments/add?
    controller: SiteController
    action: addCommentsAction
  comments_update_rating:
    pattern: /comments/rating-update/?
    controller: SiteController
    action: updateRatingAction
  active_comentators:
    pattern: /comentators/active/?{page}/?
    controller: NewsController
    action: getActiveCom
    params:
          page: ([0-9]*)



  books-list:
    pattern: /books/list/?{page}/?
    controller: BookController
    action: indexAction
    params:
      page: ([0-9]*)
  contact-us:
    pattern: /contact-us/?
    controller: SiteController
    action: contactAction
  login:
    pattern: /login/?
    controller: SecurityController
    action: loginAction
  register:
    pattern: /register/?
    controller: SecurityController
    action: registerAction
  register_confirmation:
    pattern: /confirm/?
    controller: SecurityController
    action: confirmAction
  book-show:
    pattern: /book-{id}/?
    controller: BookController
    action: showAction
    params:
      id: ([1-9]{1}[0-9]*)
  book-test-route:
    pattern: /this-is-{test}-{id}-{pat}
    controller: TestController
    action: testAction
    params:
      id: ([1-9]{1}[0-9]*)
      test: ([a-zA-Z]+)
      pat: ([\+\-\*\/]+)
  logout:
    pattern: /logout/?
    controller: SecurityController
    action: logoutAction
  add_to_cart:
    pattern: /cart/add-{id}/?
    controller: CartController
    action: addAction
    params:
      id: ([1-9]{1}[0-9]*)
  show_cart:
    pattern: /cart/list/?
    controller: CartController
    action: showAction
  delete_from_cart:
    pattern: /cart/delete-{id}/?
    controller: CartController
    action: deleteAction
    params:
      id: ([1-9]{1}[0-9]*)

#  Admin routes

  admin_index:
    pattern: /admin/index/?
    controller: Admin\SiteController
    action: indexAction
  admin_all_books:
    pattern: /admin/books/list/?{page}/?
    controller: Admin\BookController
    action: indexAction
    params:
      page: ([0-9]*)
  admin_table:
    pattern: /admin/books/table/?
    controller: Admin\BookController
    action: tableAction
  admin/book-show:
    pattern: /admin/books/show-{id}/?
    controller: Admin\BookController
    action: showAction
    params:
      id: ([1-9]{1}[0-9]*)
  admin_edit_book:
    pattern: /admin/books/edit-{id}/?
    controller: Admin\BookController
    action: editAction
    params:
      id: ([1-9]{1}[0-9]*)
  book_add:
    pattern: /admin/books/add/?
    controller: Admin\BookController
    action: addAction
  admin_delete_book:
    pattern: /admin/books/delete-{id}/?
    controller: Admin\BookController
    action: deleteAction
    params:
      id: ([1-9]{1}[0-9]*)
  change_password:
    pattern: /admin/change-pw
    controller: Admin\SecurityController
    action: changeAction

#    API routes
  api_book_list:
    pattern: /api/books/?
    controller: API\BookController
    action: indexAction
    methods:
            0: get
  api_book_item:
    pattern: /api/books/{id}/?
    controller: API\BookController
    action: showAction
    params:
      id: ([1-9]{1}[0-9]*)
    methods:
            0: get
  api_book_create:
    pattern: /api/books/?
    controller: API\BookController
    action: addAction
    methods:
            0: post
  api_book_delete:
    pattern: /api/books/{id}/?
    controller: API\BookController
    action: deleteAction
    params:
      id: ([1-9]{1}[0-9]*)
    methods:
            0: delete
  api_book_update:
      pattern: /api/books/{id}/?
      controller: API\BookController
      action: updateAction
      params:
        id: ([1-9]{1}[0-9]*)
      methods:
        0: put