<form action="" method="post">
	<label for="email">Email: </label>
	<input type="email" name="email" id="email" value=<?=$loginForm->getEmail()?>><br><br>
	<label for="password">Password: </label>
	<input type="password" id="password" name="password"><br>
	<label for="remember">Remember Me</label>
	<input type="checkbox" id="remember" name="remember">
	<button type="submit">Login</button>
</form>
