<h3>Books</h3>

<!--PAGINATION-->
<nav aria-label="Page navigation">
    <ul class="pagination">
        <?php
        $prev = array_shift($buttons);
        $next = array_pop($buttons);
        if($prev->isActive()):?>
        <li><a href="/books/list/<?=$page-1?>"><span aria-hidden="true">&laquo;</span></a></li>
        <?php else:?>
        <li class="disabled"><span aria-hidden="true">&laquo;</span></li>
        <?php endif;?>
        <?php foreach($buttons as $button):?>
            <li <?=$page == $button->getPage() ? 'class="active"' : ''?>><a href="/books/list/<?=$button->getPage()?>"><?=$button->getText()?></a></li>
         <?php endforeach; ?>
        <?php if($next->isActive()):?>
            <li><a href="/books/list/<?=$page+1?>"><span aria-hidden="true">&raquo;</span></a></li>
        <?php else:?>
            <li class="disabled"><span aria-hidden="true">&raquo;</span></li>
        <?php endif;?>
    </ul>
</nav>
<!--END Pagination-->

<div class="row">
    <?php foreach ($books as $book) : ?>
        <div class="col-md-3">
            <div class="thumbnail" style="height:420px;">
                Id: <?= $book->getId() ?><br/>
                <img class="img-responsive show-all" src="/webroot/upload/avatars/<?=$book->getId()?>.jpg"></img>
                <div class="caption">
                    <h3><?=$book->getTitle()?></h3>
                    <p>Price: <?=$book->getPrice()?> UAH</p>
                    <p>TODO:...authors...</p>
                    <p>
                        <a href="/book-<?= $book->getId() ?>" class="btn btn-primary" role="button">Details</a>
                        <a href="/cart/add-<?= $book->getId() ?>" class="btn btn-default" role="button">Add to cart</a>
                    </p>
                </div>
            </div>
        </div>

    <?php endforeach; ?>
</div>

<!--PAGINATION-->
<nav aria-label="Page navigation">
    <ul class="pagination">
        <?php
        if($prev->isActive()):?>
            <li><a href="/books/list/<?=$page-1?>"><span aria-hidden="true">&laquo;</span></a></li>
        <?php else:?>
            <li class="disabled"><span aria-hidden="true">&laquo;</span></li>
        <?php endif;?>
        <?php foreach($buttons as $button):?>
            <li <?=$page == $button->getPage() ? 'class="active"' : ''?>><a href="/books/list/<?=$button->getPage()?>"><?=$button->getText()?></a></li>
        <?php endforeach; ?>
        <?php if($next->isActive()):?>
            <li><a href="/books/list/<?=$page+1?>"><span aria-hidden="true">&raquo;</span></a></li>
        <?php else:?>
            <li class="disabled"><span aria-hidden="true">&raquo;</span></li>
        <?php endif;?>
    </ul>
</nav>
<!--END Pagination-->
