<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>MVC</title>
	<link rel="stylesheet" href="/webroot/style/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/webroot/style/css/style.css">
	<script src="/webroot/style/js/jquery-3.1.1.min.js"></script>
	<script src="/webroot/style/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
	<header>
		<ul class="nav nav-pills">
			<li role="presentation"><a href="/admin/index">Home</a></li>
			<li role="presentation"><a href="/admin/books/list">Books</a></li>
			<li role="presentation"><a href="/logout">Logout</a></li>
		</ul>
	</header>
	
	<b><?=$session->getFlash()?></b>
	<hr/>
	<?=$content?>
</body>
<script src="/webroot/style/js/navbar.js"></script>
</html>