<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>MVC</title>
	<link rel="stylesheet" href="/webroot/style/bootstrap/css/bootstrap.min.css">
	<script src="/webroot/style/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
	<header>
		<a href="/admin/index">Home</a>
		<a href="/admin/books/list">Books</a>
		<a href="/logout">Logout</a>
	</header>
	
	<b><?=$session->getFlash()?></b>
	<hr/>
	<?=$content?>
</body>
</html>