<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>MVC</title>
	<link rel="stylesheet" href="/webroot/style/bootstrap/css/bootstrap.min.css">
	<script src="/webroot/style/bootstrap/js/bootstrap.min.js"></script>
<body>
	<header>
		<a href="/home">Home</a>
		<a href="/books/list">Books</a>
		<a href="/contact-us">Contacts</a>
		<a href="/login">Login</a>
		<a href="/cart/list">Cart(<?=$session->get('cart_size', 0)?>)</a>
	</header>
	
	<b><?=$session->getFlash()?></b>
	<hr/>
	<?=$content?>
</body>
</html>