<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>MVC</title>
</head>
<body>
	<header>
		<a href="/mymvc/">Home</a>
		<a href="/mymvc/index.php?route=book/index">Books</a>
		<a href="/mymvc/index.php?route=site/contacts">Contacts</a>
		<a href="/mymvc/index.php?route=security/login">Login</a>
	</header>
	
	<b><?=\Library\Session::getFlash()?></b>
	<hr/>
	<?=$content?>
</body>
</html>